### PR TITLE
Added some more questions to C++ Interview questions list. 

### PR DESCRIPTION
**Pull request by mandepsingh**

### CODE REVIEW

**Comment by achoudh5** [comment]
Hi @mandepsingh 

Can you please resolve conflicts?

**Comment by mandepsingh** [comment]
yes offcourse.

**Comment by achoudh5** [comment]
@mandepsingh are you still working on this PR?

**Comment by mandepsingh** [comment]
@achoudh5 no i am not #13 working on this pr.

**Pull request closed without merging**
